services:
  - type: web
    name: backend_development_go
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_HOST
        value: dpg-d14pkvmmcj7s73fekpm0-a
      - key: DB_USER
        value: book_zm4y_user
      - key: DB_PASSWORD
        value: root
      - key: DB_NAME
        value: book_zm4y
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: disable
      - key: JWT_SECRET
        value: supersecure
